### ISSUE TITLE
Criar barra de ações

### ISSUE THREAD

**Issue by arqluizalves** [ramonnteixeira/kudomundo-frontend#2]
Criar barra de ações com opções de enviar novos cards e de filtrar a visualização do cards

![image](https://user-images.githubusercontent.com/55717634/65724845-a2ea9480-e087-11e9-9444-0bb60a0d2866.png)

**Comment by ramonnteixeira** [comment]
@arqluizalves , considerando a lógica do Kudo Cards, não seria bacana mais uma opção para exibir apenas os kudos do usuário logado?

**Comment by ramonnteixeira** [comment]
atualizado o ambiente.

**Comment by arqluizalves** [comment]
Ramonitos, acho que temos que liberar sim um filtro por pessoa. Porém não deixa-lo como padrão. Uma vez que a gente usa a visão do Board "padrão" nas TV's.
